id: default
disabled: true
allowed-rarities: ALL
item:
  material: FISHING_ROD
  displayname: <gradient:#E6F9FF:#8FD9FB>EvenMoreFish <yellow>Fishing Rod
  glowing: true
  lore:
    - ''
    - <gray>Catch </gray><yellow>custom </yellow><gray>fish using
    - <gray>this fishing rod.